[package]
name = "rustzee"
version = "0.1.0"
authors = ["Andrew Palmer <atp@sdf.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
text_io = "0.1.8"

[[bin]]
name = "rustzee"
path = "main.rs"
